set wshshell = wscript.CreateObject("wScript.Shell")
 wshshell.run "Notepad"
 wscript.sleep 1000
 wshshell.sendkeys "O"
 wscript.sleep 1000
 wshshell.sendkeys "N"
 wscript.sleep 1000
 wshshell.sendkeys "O"
 wscript.sleep 1000
 wshshell.sendkeys "N"
 wscript.sleep 1000
 wshshell.sendkeys "O"
 wscript.sleep 1000
 wshshell.sendkeys "N"
 wshshell.sendkeys "O"
 wscript.sleep 1000
 wshshell.sendkeys "N"
 wscript.sleep 1000
 wshshell.sendkeys "O"
 wscript.sleep 1000
 wshshell.sendkeys "N"
 wscript.sleep 1000
 wshshell.sendkeys "O"
 wscript.sleep 1000
 wshshell.sendkeys "N"
